### ISSUE TITLE
java.lang.IllegalAccessError (view does not exist)

### ISSUE THREAD

**Issue by vaibhawc** [uncomplicate/deep-diamond#1]
Occurs with 
`:require [uncomplicate.diamond.native]`

**Comment by blueberry** [comment]
Can you please provide more details? (lein project or alternative, etc.)

**Comment by vaibhawc** [comment]
Sure,
I am using gorilla-repl `[org.clojars.benfb/lein-gorilla "0.6.0"]` with "0.14.0-alpha".

**Comment by blueberry** [comment]
Can you please try an ordinary clojure/lein project and share the configuration? Then I'd be able to try this at my machine and either confirm your bug or see what you're missing.

**Comment by vaibhawc** [comment]
Oh it's a normal lein project only.
If I am doing `lein run` it gives :
`Syntax error (IllegalAccessError) compiling at (uncomplicate/diamond/internal/dnnl/factory.clj:1:1).
view does not exist`

**Comment by blueberry** [comment]
Sorry, I can't reproduce it.

**Comment by vaibhawc** [comment]
Ok, I tried to create a fresh project this time without any plugins.
It does require **successfully** now.. so that's **good** probably.. 
but I get this with it :
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`
Doesn't show this when I replace native with tensor.

Do I have to do/include something extra?

**Comment by vaibhawc** [comment]
Ok. I just figured out. The original issue occurred when I included an older version of neanderthal (0.31.0) in my project.clj explicitly.
The SLF4J thing occurs when either I don't include neanderthal or include the latest version of it (0.36.0).
Somehow I thought using neanderthal wouldn't affect anything.

**Comment by blueberry** [comment]
SLF4J is not an error. It's just a message (by a 3rd party library). Configure logging if you don't want to see it. No-op logging is provided by taoenso timbre library, for exapmle.

**Comment by vaibhawc** [comment]
Ok, so if I have to use some functions from neanderthal along with those in diamond, I have to make sure I am using correct version of it which is in sync with diamond?
