### ISSUE TITLE
`data` seems to be mssing in GitHub

### ISSUE THREAD

**Issue by behrica** [uncomplicate/deep-diamond#14]
I try to run the unit tests here, but it seems that the input data is missing:

https://github.com/uncomplicate/deep-diamond/blob/eb3051031281ca55b09663a1375ce4e57a5f6bf1/test/uncomplicate/diamond/functional/imdb_sentiment/classification_test.clj#L25

Could you add them in this GitHub repo ?

**Comment by behrica** [comment]
Yes, I found it by "coincidents" on Kaggle.
Could you maybe add "download" pointers to the test code comments or similòar ?

It is true, that they are "known datasets", but from that to the "precise working data file" can be long try-and-error.

I think it is very educative, to be able to run the functional tests by hand easily.
If you tell me the file locations, I could do a PR as well add these comments.

The data is missing for all 4 functional tests.

**Comment by behrica** [comment]
Otherwise could make the data files available in  an other form ? I have one test running and would like to run and study the others as well

**Comment by blueberry** [comment]
Sure. All that data is public, widely available at thousands of locations, and I included direct links to a primary source in the Deep Learning for Programmers book.
