### ISSUE TITLE
Doing unconstrained optimization with deep diamond.

### ISSUE THREAD

**Issue by zendevil** [uncomplicate/deep-diamond#8]
I want to do optimization on some tensors, and I have certain constraints, where the constrained optimization problem is taken from section 4.2 of the following paper:

http://groups.csail.mit.edu/rrg/papers/BryIJRR15.pdf

Basically I want to find a substitute for numpy's optimize.minimize function. Is there such a function in deep diamond that would do unconstrained optimization on tensors or does one have to write their own function?

**Comment by blueberry** [comment]
This is out of scope of DD.
